# Generated by Django 4.0.6 on 2022-07-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(max_length=15)),
                ('transaction', models.CharField(max_length=15)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField()),
                ('expirydate', models.DateTimeField()),
                ('cardtype', models.CharField(max_length=15)),
                ('dateissued', models.DateTimeField()),
                ('issuer', models.CharField(max_length=15)),
                ('securitycode', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField()),
                ('nationality', models.CharField(max_length=15)),
                ('idnumber', models.CharField(max_length=15)),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.SmallIntegerField()),
                ('marritualstatus', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=15)),
                ('employmentstatus', models.BooleanField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestrate', models.IntegerField()),
                ('loanbalance', models.IntegerField()),
                ('dateandtime', models.DateTimeField()),
                ('paymentduedate', models.DateTimeField()),
                ('loan_type', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=15)),
                ('dateandtimecreated', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptdate', models.DateTimeField()),
                ('totalamount', models.IntegerField()),
                ('receiptfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
                ('transaction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactioncost', models.IntegerField()),
                ('location', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('transactioncoast', models.IntegerField()),
                ('account', models.CharField(max_length=15)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=15)),
                ('transactionamount', models.IntegerField()),
                ('transactiontype', models.CharField(max_length=15)),
                ('transactioncharge', models.IntegerField()),
                ('dateandtime', models.DateTimeField()),
                ('thirdparty', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('pin', models.SmallIntegerField()),
                ('datecreated', models.DateTimeField()),
                ('isActive', models.BooleanField()),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
