# Generated by Django 4.0.6 on 2022-08-01 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_thirdparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('bonus', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_transaction', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=15, null=True)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_file', models.FileField(upload_to='')),
                ('total_amount', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_transaction', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_id', models.IntegerField()),
                ('name', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notifications_receipt', to='wallet.thirdparty')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.IntegerField()),
                ('loan_type', models.CharField(max_length=15, null=True)),
                ('amount', models.IntegerField()),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest_rate', models.IntegerField()),
                ('pay_due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_balance', models.IntegerField()),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_guarantor', to='wallet.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='wallet.account')),
            ],
        ),
    ]
