# Generated by Django 4.0.6 on 2022-08-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_reward_receipt_notification_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='Symbol',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='occupation',
        ),
    ]
